using Xunit;

namespace Leaf.Plugins.Nova.Tests;

public sealed class AgentWorkspaceTests
{
    [Fact]
    public void GenerateClaudeMdPlacesScratchConventionInHarnessInstructions()
    {
        var root = Path.Combine(Path.GetTempPath(), $"nova-agent-workspace-{Guid.NewGuid():N}");

        try
        {
            var workspace = new AgentWorkspace(root);
            workspace.EnsureDirectories();

            workspace.GenerateClaudeMd();

            foreach (var fileName in new[] { "AGENTS.md", "CLAUDE.md" })
            {
                var content = File.ReadAllText(Path.Combine(root, fileName));
                Assert.Contains("REDLEAF_SCRATCH_DIR", content);
                Assert.Contains("disposable workspace", content);
            }
        }
        finally
        {
            if (Directory.Exists(root))
                Directory.Delete(root, recursive: true);
        }
    }

    [Fact]
    public void GeneratedReadOnlyHarnessProjectionIsNeverMaterializedOrOverwritten()
    {
        var root = Path.Combine(Path.GetTempPath(), $"nova-generated-workspace-{Guid.NewGuid():N}");
        Directory.CreateDirectory(root);
        var expected = "generated by RedLeaf";
        var paths = new[] { "AGENTS.md", "CLAUDE.md" }
            .Select(name => Path.Combine(root, name))
            .ToArray();

        try
        {
            foreach (var path in paths)
            {
                File.WriteAllText(path, expected);
                File.SetAttributes(path, FileAttributes.ReadOnly);
            }
            var workspace = new AgentWorkspace(root);

            Assert.True(workspace.UsesGeneratedHarnessProjection());
            workspace.GenerateClaudeMd();

            foreach (var path in paths)
                Assert.Equal(expected, File.ReadAllText(path));
        }
        finally
        {
            foreach (var path in paths)
                if (File.Exists(path)) File.SetAttributes(path, FileAttributes.Normal);
            if (Directory.Exists(root)) Directory.Delete(root, recursive: true);
        }
    }
}
