using System.Net.Http;
using System.Text;
using System.Text.Json;
using Nova.App.Configuration;
using RedBamboo.AppHost.Logging;

namespace Nova.App.Services;

/// <summary>
/// At startup, fetches /discover from the sibling Red Suite services and writes a
/// deterministic, AI-readable endpoint reference to config/runtime/suite-apis.md.
/// The generated CLAUDE.md points Nova at this file as the authoritative API surface.
/// </summary>
public static class SuiteDiscoveryService
{
    private const string OutputPath = "config/runtime/suite-apis.md";

    public static async Task RefreshAsync(NovaConfig config, MemoryManager memory, LogService log)
    {
        try
        {
            using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(3) };

            // Deterministic order: fixed suite roster, lowest port first.
            (string Label, string BaseUrl)[] targets =
            [
                ("RedCompute", config.Suite.RedCompute),
                ("CodeRed", config.Suite.CodeRed),
                ("RedMatter", config.Suite.RedMatter),
                ("RedLeaf", config.Suite.RedLeaf),
            ];

            var sb = new StringBuilder();
            sb.AppendLine("# Red Suite — live API reference");
            sb.AppendLine();
            sb.AppendLine($"> Generated by Nova at startup ({DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC) from each service's /discover.");
            sb.AppendLine("> Do not edit — regenerated every launch. Trust this file over memory; APIs evolve.");
            sb.AppendLine("> Required parameters are marked with `*`.");
            sb.AppendLine();

            var online = 0;
            foreach (var (label, baseUrl) in targets)
            {
                if (await TryAppendServiceAsync(http, sb, label, baseUrl)) online++;
            }

            memory.WriteMemoryFile(OutputPath, sb.ToString());
            log.Info("discovery", $"Suite API reference written ({online}/{targets.Length} services online)");
        }
        catch (Exception ex)
        {
            log.Warn("discovery", $"Failed to write suite API reference: {ex.Message}");
        }
    }

    private static async Task<bool> TryAppendServiceAsync(HttpClient http, StringBuilder sb, string label, string baseUrl)
    {
        JsonElement root;
        try
        {
            var json = await http.GetStringAsync($"{baseUrl.TrimEnd('/')}/discover");
            using var doc = JsonDocument.Parse(json);
            root = doc.RootElement.Clone();
        }
        catch
        {
            sb.AppendLine($"## {label} — {baseUrl}");
            sb.AppendLine();
            sb.AppendLine("_Offline at startup — endpoints unknown. Probe `GET /discover` when it is back._");
            sb.AppendLine();
            return false;
        }

        var name = GetString(root, "name") ?? GetString(root, "service") ?? label;
        var apiBase = GetString(root, "api_base") ?? baseUrl;
        var description = GetString(root, "description");

        sb.AppendLine($"## {name} — {apiBase}");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(description))
        {
            sb.AppendLine(description);
            sb.AppendLine();
        }

        if (root.TryGetProperty("app_endpoints", out var endpoints) && endpoints.ValueKind == JsonValueKind.Array)
        {
            foreach (var ep in endpoints.EnumerateArray())
            {
                var method = GetString(ep, "method") ?? "GET";
                var path = GetString(ep, "path") ?? "?";
                var desc = GetString(ep, "description") ?? "";
                var line = $"- {method} {path} — {desc}";

                if (ep.TryGetProperty("parameters", out var pars) && pars.ValueKind == JsonValueKind.Array)
                {
                    var names = pars.EnumerateArray()
                        .Select(p => GetString(p, "name") + (GetBool(p, "required") ? "*" : ""))
                        .Where(n => !string.IsNullOrEmpty(n))
                        .ToList();
                    if (names.Count > 0)
                        line += $" (params: {string.Join(", ", names)})";
                }

                sb.AppendLine(line);
            }
            sb.AppendLine();
        }

        if (root.TryGetProperty("proxies", out var proxies) && proxies.ValueKind == JsonValueKind.Array)
        {
            var any = false;
            foreach (var proxy in proxies.EnumerateArray())
            {
                if (!any)
                {
                    sb.AppendLine("### Proxied prefixes");
                    sb.AppendLine();
                    any = true;
                }
                var prefix = GetString(proxy, "prefix") ?? "?";
                var upstream = GetString(proxy, "upstream") ?? "?";
                sb.AppendLine($"- {prefix}/** → {upstream} (see {GetString(proxy, "discover") ?? upstream + "/discover"})");
            }
            if (any) sb.AppendLine();
        }

        return true;
    }

    private static string? GetString(JsonElement el, string prop)
        => el.ValueKind == JsonValueKind.Object && el.TryGetProperty(prop, out var v) && v.ValueKind == JsonValueKind.String
            ? v.GetString()
            : null;

    private static bool GetBool(JsonElement el, string prop)
        => el.ValueKind == JsonValueKind.Object && el.TryGetProperty(prop, out var v) && v.ValueKind == JsonValueKind.True;
}
